[package]
org = "ballerinax"
name = "github_new_commit_to_google_sheet_row"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.14"

[[dependency]]
org = "ballerinax"
name = "googleapis.sheets"
version = "0.99.8"
