[package]
template = true
keywords = ["Kind/Sample", "Type/Webhook", "Category/Integration"]
org = "choreo"
displayName = "Salesforce New Contact to Twilio SMS"
name = "sfdc_new_contact_to_twilio_sms"
icon = "icon.png"
description = "Send a Twilio SMS to a phone number when a new contact is created in a specific Salesforce account"
distribution = "2201.3.1"
version = "3.1.0"
[build-options]
observabilityIncluded = true
